/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a dockadaptor -i kbddock.h -l KbdDock /home/edge/progects/qtvkbd/src/org.kde.qtvkbd.Dock.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dockadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DockAdaptor
 */

DockAdaptor::DockAdaptor(KbdDock *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DockAdaptor::~DockAdaptor()
{
    // destructor
}

bool DockAdaptor::visible() const
{
    // get the value of property visible
    return qvariant_cast< bool >(parent()->property("visible"));
}

void DockAdaptor::setVisible(bool value)
{
    // set the value of property visible
    parent()->setProperty("visible", QVariant::fromValue(value));
}


#include "dockadaptor.moc"
