/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a dockadaptor -i kbddock.h -l KbdDock /home/edge/progects/qtvkbd/src/org.kde.qtvkbd.Dock.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DOCKADAPTOR_H
#define DOCKADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "kbddock.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.kde.qvkbd.Dock
 */
class DockAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.qvkbd.Dock")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.qvkbd.Dock\">\n"
"    <property access=\"readwrite\" type=\"b\" name=\"visible\"/>\n"
"  </interface>\n"
        "")
public:
    DockAdaptor(KbdDock *parent);
    virtual ~DockAdaptor();

    inline KbdDock *parent() const
    { return static_cast<KbdDock *>(QObject::parent()); }

public: // PROPERTIES
    Q_PROPERTY(bool visible READ visible WRITE setVisible)
    bool visible() const;
    void setVisible(bool value);

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
