/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a qtvkbdadaptor -i mainwidget.h -l MainWidget /home/edge/progects/qtvkbd/src/org.kde.qtvkbd.Qtvkbd.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QTVKBDADAPTOR_H
#define QTVKBDADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "mainwidget.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.kde.qvkbd.Qvkbd
 */
class QvkbdAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.qvkbd.Qvkbd")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.qvkbd.Qvkbd\">\n"
"    <property access=\"read\" type=\"b\" name=\"alone\"/>\n"
"    <property access=\"readwrite\" type=\"b\" name=\"visible\"/>\n"
"    <property access=\"readwrite\" type=\"b\" name=\"locked\"/>\n"
"  </interface>\n"
        "")
public:
    QvkbdAdaptor(MainWidget *parent);
    virtual ~QvkbdAdaptor();

    inline MainWidget *parent() const
    { return static_cast<MainWidget *>(QObject::parent()); }

public: // PROPERTIES
    Q_PROPERTY(bool alone READ alone)
    bool alone() const;

    Q_PROPERTY(bool locked READ locked WRITE setLocked)
    bool locked() const;
    void setLocked(bool value);

    Q_PROPERTY(bool visible READ visible WRITE setVisible)
    bool visible() const;
    void setVisible(bool value);

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
